import importlib.util
import json
import os
from pathlib import Path
import subprocess
import shutil
import tempfile
import unittest

SCRIPT = Path(__file__).resolve().parents[2] / "scripts/verify_attribution.py"
spec = importlib.util.spec_from_file_location("verify_attribution", SCRIPT)
guard = importlib.util.module_from_spec(spec)
spec.loader.exec_module(guard)


class MetadataTests(unittest.TestCase):
    def test_exact_identity(self):
        guard.check_identity(guard.AUTHOR_NAME, guard.AUTHOR_EMAIL, "commit")
        for name, email in [("Other", guard.AUTHOR_EMAIL), (guard.AUTHOR_NAME, "wrong@example.com")]:
            with self.assertRaises(guard.Violation):
                guard.check_identity(name, email, "commit")

    def test_real_credit_forms_are_rejected(self):
        for text in [
            "Fix parser\n\nCo-Authored-By: Helper <helper@example.com>",
            "Generated with [Claude Code](https://claude.ai/code)",
            "Implemented by Codex", "Thanks to ChatGPT", "AI-assisted change",
            "Reviewed-by: assistant", "Not by Codex",
            "Implemented by **Claude**", "Reviewed using Claude", "Fix parser\n\nAnthropic",
            "Fix parser \U0001f916", "Fix parser\u2014preserve bytes",
        ]:
            with self.subTest(text=text), self.assertRaises(guard.Violation):
                guard.check_text(text, "metadata")

    def test_instruction_and_legal_mentions_are_not_credits(self):
        for text in [
            "Check commit metadata for assistant credit trailers",
            "Preserve third-party copyright and Apache-2.0 notices",
        ]:
            guard.check_text(text, "metadata")

    def test_pr_title_and_body_checked_with_real_head(self):
        event = {"pull_request": {"title": "Fix parser", "body": "Keep bytes unchanged", "head": {"sha": "a" * 40}}}
        self.assertEqual(guard.check_event(event), "a" * 40)
        for field in ("title", "body"):
            bad = json.loads(json.dumps(event))
            bad["pull_request"][field] = "Written by Codex"
            with self.assertRaises(guard.Violation):
                guard.check_event(bad)

    def test_release_event_and_malformed_metadata(self):
        guard.check_event({"release": {"name": "Alpha.17", "body": "Tested migrations"}})
        for event in [[], {"pull_request": []}, {"pull_request": {"head": {}, "title": 1}}, {"after": "main"}, {"release": {"body": "Co-authored-by: helper"}}]:
            with self.assertRaises(guard.Violation):
                guard.check_event(event)


class GitMetadataTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.env = os.environ.copy()
        for key in ("GIT_AUTHOR_NAME", "GIT_AUTHOR_EMAIL", "GIT_COMMITTER_NAME", "GIT_COMMITTER_EMAIL", "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"):
            self.env.pop(key, None)
        self.run_git("init", "-q")
        self.run_git("config", "user.name", guard.AUTHOR_NAME)
        self.run_git("config", "user.email", guard.AUTHOR_EMAIL)
        self.run_git("-c", "core.hooksPath=", "commit", "--allow-empty", "-qm", "Initial source")

    def tearDown(self):
        self.temp.cleanup()

    def run_git(self, *args):
        return subprocess.run(["git", "-C", str(self.root), *args], check=True, capture_output=True, env=self.env)

    def test_good_repository_and_legal_file(self):
        (self.root / "NOTICE").write_text("Generated by a third-party copyright holder")
        (self.root / "AGENTS.md").write_text("Do not add Co-Authored-By trailers")
        guard.check_repository(self.root)

    def test_actual_commit_credit_rejected(self):
        self.run_git("-c", "core.hooksPath=", "commit", "--allow-empty", "-qm", "Fix\n\nCo-authored-by: helper")
        with self.assertRaises(guard.Violation):
            guard.check_repository(self.root)

    def test_actual_wrong_author_rejected(self):
        self.run_git("-c", "core.hooksPath=", "commit", "--allow-empty", "--author", "Someone Else <other@example.com>", "-qm", "Fix")
        with self.assertRaises(guard.Violation):
            guard.check_repository(self.root)

    def test_actual_tag_annotation_rejected(self):
        self.run_git("tag", "-a", "v1", "-m", "Generated with Claude Code")
        with self.assertRaises(guard.Violation):
            guard.check_repository(self.root)

    def test_obsolete_commit_reachable_only_through_tag_is_rejected(self):
        self.run_git("-c", "core.hooksPath=", "commit", "--allow-empty", "-qm", "Old change\n\nCo-authored-by: helper")
        self.run_git("tag", "-a", "old-release", "-m", "Historical release")
        self.run_git("reset", "--hard", "HEAD~1")
        with self.assertRaises(guard.Violation):
            guard.check_repository(self.root)

    def test_staged_release_notes_are_checked(self):
        notes = self.root / "docs/releases/v1.md"
        notes.parent.mkdir(parents=True)
        notes.write_text("Written by Codex")
        self.run_git("add", "docs/releases/v1.md")
        notes.write_text("Clean working copy does not conceal staged credit")
        with self.assertRaises(guard.Violation):
            guard.check_notes(self.root, staged=True)

    def install_hook(self):
        scripts = self.root / "scripts"
        scripts.mkdir()
        shutil.copy2(SCRIPT, scripts / SCRIPT.name)
        hooks = self.root / ".githooks"
        hooks.mkdir()
        hook = hooks / "commit-msg"
        shutil.copy2(SCRIPT.parents[1] / ".githooks/commit-msg", hook)
        hook.chmod(0o755)
        self.run_git("config", "core.hooksPath", ".githooks")

    def attempt_commit(self, *args):
        return subprocess.run(
            ["git", "-C", str(self.root), "commit", "--allow-empty", *args],
            capture_output=True, env=self.env,
        )

    def test_commit_hook_accepts_sole_author(self):
        self.install_hook()
        result = self.attempt_commit("-qm", "Preserve verified source bytes")
        self.assertEqual(result.returncode, 0, result.stderr.decode())

    def test_commit_hook_refuses_credit_and_author_override(self):
        self.install_hook()
        for args in [
            ("-qm", "Generated with Claude Code"),
            ("--author", "Helper <helper@example.com>", "-qm", "Preserve bytes"),
        ]:
            result = self.attempt_commit(*args)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn(b"attribution check failed", result.stderr)


if __name__ == "__main__":
    unittest.main()
